# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HoverConversionSample' do
pod 'HoverConversion', :path => '../'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'TouchVisualizer', '~>1.4.0'
end

